-- Calling this C++ function will throw std::runtime_error
cpp_throw_exception()
